bug#0000034: wrapper script complains about more errors

diff --git a/bin/netmrg_cron.sh.in b/bin/netmrg_cron.sh.in
--- a/bin/netmrg_cron.sh.in
+++ b/bin/netmrg_cron.sh.in
@@ -29,3 +29,22 @@ if [ -e $lockfile ] ; then
 fi
 
 $netmrg > $output 2> $error
+exitval=$?
+
+if [ $exitval == 2 ] ; then
+	echo "NetMRG failed to create a lockfile.  Perhaps another copy is running?" | mail -s "NetMRG lockfile present at $curdate" $mailto
+	mv -f $output $output.$curdate
+	mv -f $error $error.$curdate
+elif [ $exitval == 3 ] ; then
+	echo "NetMRG failed to establish a database connection" | mail -s "NetMRG database connect failed at $curdate" $mailto
+	mv -f $output $output.$curdate
+	mv -f $error $error.$curdate
+elif [ $exitval == 254 ] ; then
+	echo "NetMRG lockfile present at start. Perhaps another copy is running" | mail -s "NetMRG lockfile is present at $curdate" $mailto
+	mv -f $output $output.$curdate
+	mv -f $error $error.$curdate
+elif [ $exitval != 0 ] ; then
+	echo "NetMRG exited abnormally" | mail -s "NetMRG exited abnormally at $curdate" $mailto
+	mv -f $output $output.$curdate
+	mv -f $error $error.$curdate
+fi
